name: zip-release-files
on:
  push:
    tags:
      - v*
jobs:
  zip-release-files:
    runs-on: windows-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Zip release files
        run: .\Prepare-Release.ps1 ${{ github.ref_name }}
        shell: powershell
